### ISSUE TITLE
gedit 3.34

### ISSUE THREAD

**Issue by speendo** [AndrewJamesTurner/openSCAD-lang-file#1]
Hi!

Thank you for this script!

I was using this lang-file since a couple of years. However, it doesn't seem to work with the resent version of gedit (3.34) on my Debian system.

Is it possible, that there were some changes in the API that should be followed for `openSCAD-lang-file`?

**Comment by AndrewJamesTurner** [comment]
Hi @speendo 

I'm glad it been working for you for so long! Unfortunately I'm no longer perusing 3D modelling as a hobby so I'm unlike to fix this. 

I am of cause happy to accept pull requests if you fix it.

Thanks!

Andy

**Comment by speendo** [comment]
Thank you for your reply!

Updating the script seems possible. However, can you give me a hint on where to find a recent documentation on how a language file should look like?

Thank you and best regards!

**Comment by speendo** [comment]
Note to self: this Reference should do:
https://developer.gnome.org/gtksourceview/stable/lang-reference.html

**Comment by tengwar** [comment]
Since #2 was merged, shoudn't this bug be closed? It seems to work fine in Gedit 40.1.

**Comment by AndrewJamesTurner** [comment]
Thanks for the reminder @tengwar
